version: "3.8"

services:
  web:
    build: .
    ports:
      - 5000:5000
    env_file: .env
    depends_on:
      - redis
    volumes:
      - ./:/app

  redis:
    image: redis:alpine
    volumes:
      - redis-data:/data

volumes:
  redis-data: