version: "3.8"

services:
  app:
    container_name: full-feed
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    environment:
      - REDIS_URL=redis://redis
      - PORT=5000
    volumes:
      - ./:/app

  redis:
    container_name: full-feed-redis
    image: redis:alpine
    volumes:
      - redis-data:/data

volumes:
  redis-data: